# wrangler.toml
name = "my-app"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[[d1_databases]]
binding = "DB" # This is the name we use in code
database_name = "example"
database_id = "eb2dbfd1-c591-49b2-94e1-71277a8c790b"
migrations_dir = "drizzle"